### ISSUE TITLE
'boolean' does not name a type

### ISSUE THREAD

**Issue by andyseubert** [CaptIgmu/Adafruit_HDC1000#1]
Veryfing code using this library in Particle Build fails with this error:
```
Adafruit_HDC1000/Adafruit_HDC1000.h:46:3: error: 'boolean' does not name a type
   boolean begin(uint8_t a = HDC1000_I2CADDR)

**Comment by CaptIgmu** [comment]
Andrew,
It appears the behavior of the Particle Build IDE has changed over time. 
To correct this, I added:
     #include "application.h"   to Adafruit_HDC1000.h file  on GitHub

I had this in all of my local builds; I don't compile much with Build IDE !

These libraries were migrated from Arduino where you could use boolean 
instead of bool, uint32_t instead of
unsigned int, etc. /*Photons/Electrons need #include "application.h"*/  !

Thank you for your feedback,
Ron B.
